"""add sagas and character saga relationship

Revision ID: 74762ff23075
Revises: fb56718e856d
Create Date: 2026-10-03 23:13:36.976470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74762ff23075'
down_revision: Union[str, Sequence[str], None] = 'fb56718e856d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sagas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character_saga',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('saga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'saga_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_saga')
    op.drop_table('sagas')
    # ### end Alembic commands ###
